src = 
check.c \             
instruction.c \      
malloc.c \           
print.c \
copy_entry.c \        
main.c \             
one_argument.c \      
split.c \
free.c \             
main.h \             
principal_checker.c \
utility.c \


